/*
 * (C) Copyright 2008-2009 STMicroelectronics.
 *
 * Sean McGoogan <Sean.McGoogan@st.com>
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#ifndef __CONFIG_H
#define __CONFIG_H

#include "describe_autogenerated.h"
/*
 * High Level Configuration Options
 * (easy to change)
 */

#define CONFIG_SH4	1		/* This is an SH4 CPU		*/
#define CONFIG_CPU_SUBTYPE_SH4_3XX	/* it is an SH4-300		*/

// YWDRIVER_MODI sqy 2008/12/2 begin
#define CONFIG_MENUKEY ' '


#define START_UPDATE_CHAR   1           //SOH
#define BOOT_UPDATE_CHAR    17          //DC1
#define KERNEL_UPDATE_CHAR  18          //DC2
#define FS_UPDATE_CHAR      19          //DC3
#define ALL_UPDATE_CHAR     20          //DC4
#define FINISH_UPDATE_CHAR  24          //CAN
#define FAIL_UPDATE_CHAR    27          //ESC
#define P_CLOCK_RATE	    87500000	/* clock rate for CSP		*/


#define	RAW_KEY_MENU	    128
#define	RAW_KEY_OK		    8
#define	RAW_KEY_UP			4
#define	RAW_KEY_DOWN		32
#define	RAW_KEY_LEFT		2
#define	RAW_KEY_RIGHT		16
// YWDRIVER_MODI sqy 2008/12/2 end

/*-----------------------------------------------------------------------
 *	Jumper settings to select between the SoC's 3 boot-modes:
 *		a) boot from NOR flash
 *		b) boot from NAND flash
 *		c) boot from SPI serial flash
 *
 *	With the LED display panel facing the user:
 *
 *	Jumper	Location	NOR	NAND	SPI
 *	------	--------	---	----	---
 *	JE6	top-most	EAST	EAST	WEST
 *	JE5	below JE6	EAST	WEST	EAST
 *	JE3	left-side	NORTH	SOUTH	SOUTH
 *	JE2	right-side	SOUTH	NORTH	NORTH
 */


/*-----------------------------------------------------------------------
 * Are we booting directly from a NAND Flash device ?
 * If so, then define the "CFG_BOOT_FROM_NAND" macro,
 * otherwise (e.g. NOR/SPI Flash booting), do not define it.
 */
#undef CFG_BOOT_FROM_NAND		/* define to build a NAND-bootable image */
//#define CFG_BOOT_FROM_NAND  //YWDRIVER_MODI lwj add

/*-----------------------------------------------------------------------
 * Are we booting directly from a SPI Serial Flash device ?
 * If so, then define the "CFG_BOOT_FROM_SPI" macro,
 * otherwise (e.g. for NOR/NAND Flash booting), do not define it.
 */
#undef CFG_BOOT_FROM_SPI		/* define to build a SPI-bootable image */
#define CFG_BOOT_FROM_SPI

/*-----------------------------------------------------------------------
 * Start addresses for the final memory configuration
 * Assume we run out of uncached memory for the moment
 */

#if defined(CFG_BOOT_FROM_SPI)		/* we are booting from SPI, so *DO* swap CSA and CSC with JE2 */
#define CFG_EMI_SPI_BASE	0xA0000000	/* CSA: SPI Flash,  Physical 0x00000000 (64MiB) */
#define CFG_EMI_NOR_BASE	0xA0000000	/* CSB: NOR Flash,  Physical 0x04000000 (32MiB) */
#define CFG_EMI_NAND_BASE	0xA6000000	/* CSC: NAND Flash, Physical 0x06000000 (8MiB) */
#define CFG_NAND_FLEX_CSn_MAP	{ 0 }		/* NAND is on Chip Select CSA */
#elif defined(CFG_BOOT_FROM_NAND)	/* we are booting from NAND, so *DO* swap CSA and CSC with JE2 */
#define CFG_EMI_NAND_BASE	0xA0000000	/* CSA: NAND Flash, Physical 0x00000000 (64MiB) */
#define CFG_EMI_NOR_BASE	0xA4000000	/* CSB: NOR Flash,  Physical 0x04000000 (32MiB) */
#define CFG_NAND_FLEX_CSn_MAP	{ 0 }		/* NAND is on Chip Select CSA */
#else					/* else, do *NOT* swap CSA and CSC using JE2 */
#define CFG_EMI_NOR_BASE	0xA0000000	/* CSA: NOR Flash,  Physical 0x00000000 (64MiB) */
#define CFG_EMI_NAND_BASE	0xA6000000	/* CSC: NAND Flash, Physical 0x06000000 (8MiB) */
#define CFG_NAND_FLEX_CSn_MAP	{ 2 }		/* NAND is on Chip Select CSC */
#endif /* CFG_BOOT_FROM_NAND */

#ifdef CONFIG_SH_SE_MODE
#define CFG_FLASH_BASE		CFG_EMI_NOR_BASE/* NOR FLASH (uncached) via PMB */
#define CFG_SE_PHYSICAL_BASE	0x40000000	/* LMI Physical Address */
#define CFG_SDRAM_BASE		0x80000000      /* LMI    Cached addr via PMB */
#define CFG_SE_UNACHED_BASE	0x90000000	/* LMI UN-cached addr via PMB */
#define CFG_SE_SDRAM_WINDOW	(CFG_SDRAM_SIZE-1)
#else
#define CFG_FLASH_BASE		CFG_EMI_NOR_BASE/* NOR FLASH in P2 region */
#define CFG_SDRAM_BASE		0x8C000000      /* SDRAM in P1 region */
#endif

#define CFG_SDRAM_SIZE		0x10000000	/* 256 MiB of LMI SDRAM */

#if 0  //YWDRIVER_MODI lwj modify begin
#define CFG_MONITOR_LEN		0x00040000	/* Reserve 256 KiB for Monitor */
#else
#define CFG_MONITOR_LEN		0x00100000	/* 1M for Monitor :uboot+env param*/
#endif

#ifdef CFG_BOOT_FROM_NAND //YWDRIVER_MODI lwj add begin
#define CFG_MONITOR_BASE        CFG_EMI_NAND_BASE
#elif defined(CFG_BOOT_FROM_SPI) //YWDRIVER_MODI lwj add begin
#define CFG_MONITOR_BASE        CFG_EMI_SPI_BASE
#else
#define CFG_MONITOR_BASE        CFG_FLASH_BASE
#endif  //YWDRIVER_MODI lwj add end


#define CFG_MALLOC_LEN		(1 << 20)	/* Reserve 1 MiB for malloc */
#define CFG_BOOTPARAMS_LEN	(128 << 10)	/* 128 KiB */
#define CFG_GBL_DATA_SIZE	1024		/* Global data structures */

#define CFG_MEMTEST_START	CFG_SDRAM_BASE
#define CFG_MEMTEST_END		(CFG_SDRAM_BASE + CFG_SDRAM_SIZE - (3 << 20))

#define CONFIG_BAUDRATE		115200
#define CFG_BAUDRATE_TABLE	{ 9600, 19200, 38400, 57600, 115200 }

#define XSTR(s) STR(s)
#define STR(s) #s

#define BOARD pdk7105

#ifdef YW_GIT_VERSION
#define CONFIG_YW_VERSION_ON_ARG YW_GIT_VERSION
#else
#define CONFIG_YW_VERSION_ON_ARG "YW 1.1.003 Exp"
#endif

#if 0  //YWDRIVER_MODI lwj remove , we don't need this
#if CFG_MONITOR_LEN == 0x00020000		/* 128 KiB */
#	define MONITOR_SECTORS	"1:0"		/* 1 sector */
#elif CFG_MONITOR_LEN == 0x00040000		/* 256 KiB */
#	define MONITOR_SECTORS	"1:0-1"		/* 2 sectors */
#else						/* unknown */
#	error "Unable to determine sectors for monitor"
#endif
#endif

//YWDRIVER_MODI lwj add begin
#define CFG_YW_SPARK_KERNEL_LEN		" 0x00a00000 "
#define CFG_YW_SPARK_KERNEL_BASE	" 0x00100000 "
#define CFG_YW_SPARK_USERFS_LEN		" 0x16c00000 "
#define CFG_YW_SPARK_USERFS_BASE	" 0x01400000 "

#define CFG_YW_ENIGMA2_KERNEL_LEN	" 0x00800000 "
#define CFG_YW_ENIGMA2_KERNEL_BASE	" 0x18000000 "
#define CFG_YW_ENIGMA2_USERFS_LEN	" 0x07700000 "
#define CFG_YW_ENIGMA2_USERFS_BASE	" 0x18800000 "


#define CFG_YW_LOADU_UBOOT			"fatload usb 0 $load_addr "CFG_UBOOT
#define CFG_YW_TFTP_UBOOT			"tftp $load_addr "CFG_UBOOT

#define CFG_YW_LOADU_KERNEL			"fatload usb 0 $load_addr $kernel_name"
#define CFG_YW_LOADU_KERNEL_SPARK	"fatload usb 0 $load_addr "CFG_SPARK_KERNEL_NAME
#define CFG_YW_LOADU_KERNEL_ENIGMA2	"fatload usb 0 $load_addr "CFG_ENIGMA2_KERNEL_NAME

#define CFG_YW_TFTP_KERNEL			"tftp $load_addr $tftp_kernel_name"
#define CFG_YW_TFTP_KERNEL_SPARK	"tftp $load_addr "CFG_SPARK_KERNEL_NAME
#define CFG_YW_TFTP_KERNEL_ENIGMA2	"tftp $load_addr "CFG_ENIGMA2_KERNEL_NAME

#define CFG_YW_LOADU_USERFS			"fatload usb 0 $load_addr $userfs_name"
#define CFG_YW_LOADU_USERFS_SPARK	"fatload usb 0 $load_addr "CFG_SPARK_USERFS_NAME
#define CFG_YW_LOADU_USERFS_ENIGMA2	"fatload usb 0 $load_addr "CFG_ENIGMA2_USERFS_NAME

#define CFG_YW_TFTP_USERFS			"tftp $load_addr $tftp_userfs_name"
#define CFG_YW_TFTP_USERFS_SPARK	"tftp $load_addr "CFG_SPARK_USERFS_NAME
#define CFG_YW_TFTP_USERFS_ENIGMA2	"tftp $load_addr "CFG_ENIGMA2_USERFS_NAME

#if defined(CONFIG_YW_XPROG)
#define CFG_YW_BOOTCMD_SPARK												\
		"usb start;fatload usb 0 " XSTR(CFG_LOAD_ADDR) " /"CFG_SPARK_KERNEL_NAME";"\
		"bootm " XSTR(CFG_LOAD_ADDR)
#else
#if defined(CFG_BOOT_FROM_NAND) || defined(CFG_BOOT_FROM_SPI)
#define CFG_YW_BOOTCMD_SPARK												\
		"nboot.i " XSTR(CFG_LOAD_ADDR) " 0 " CFG_YW_SPARK_KERNEL_BASE ";"	\
		"bootm " XSTR(CFG_LOAD_ADDR)
#else
#define CFG_YW_BOOTCMD_SPARK "bootm " CFG_YW_SPARK_KERNEL_BASE
#endif
#endif

#define CFG_YW_BOOTCMD_ENIGMA2												\
		"nboot.i " XSTR(CFG_LOAD_ADDR) " 0 " CFG_YW_ENIGMA2_KERNEL_BASE ";"	\
		"bootm " XSTR(CFG_LOAD_ADDR)

#define CFG_YW_BOOTCMD		CFG_YW_BOOTCMD_SPARK

#if defined(CFG_BOOT_FROM_NAND)
#define CFG_YW_UPDATE_UBOOT "nand erase $monitor_base $monitor_len"			\
							"nand write.i $load_addr $monitor_base $monitor_len"
#elif defined(CFG_BOOT_FROM_SPI)
#define CFG_YW_UPDATE_UBOOT "eeprom write $load_addr $monitor_base $monitor_len"
#define CFG_YW_ERASE_UBOOT_ENV "mw.b $load_addr 0 " XSTR(CFG_ENV_SIZE) ";"	\
					"eeprom write $load_addr 0x000a0000 "XSTR(CFG_ENV_SIZE)
#else
#define CFG_YW_UPDATE_UBOOT "protect off $monitor_sec;"						\
							"erase $monitor_sec;"							\
							"cp.b $load_addr $monitor_base $monitor_len;"	\
							"protect on $monitor_sec"
#endif

#define CFG_YW_ERASE_CMD				"nand erase"
#define CFG_YW_WRITE_CMD				"nand write.i"
#define CFG_YW_WRITE_USERFS_SPARK_CMD	"nand write.yaffs2"
#define CFG_YW_WRITE_USERFS_ENIGMA2_CMD	"nand write.jffs2"

#define CFG_YW_ERASE_KERNEL_SPARK 		CFG_YW_ERASE_CMD " "			\
											CFG_YW_SPARK_KERNEL_BASE	\
											CFG_YW_SPARK_KERNEL_LEN
#define CFG_YW_WRITE_KERNEL_SPARK 		CFG_YW_WRITE_CMD " "			\
											XSTR(CFG_LOAD_ADDR) 		\
											CFG_YW_SPARK_KERNEL_BASE 	\
											"$filesize"
#define CFG_YW_UPDATE_KERNEL_SPARK		CFG_YW_ERASE_KERNEL_SPARK ";"	\
											CFG_YW_WRITE_KERNEL_SPARK
#define CFG_YW_ERASE_KERNEL_ENIGMA2		CFG_YW_ERASE_CMD " "			\
											CFG_YW_ENIGMA2_KERNEL_BASE	\
											CFG_YW_ENIGMA2_KERNEL_LEN
#define CFG_YW_WRITE_KERNEL_ENIGMA2		CFG_YW_WRITE_CMD " "			\
											XSTR(CFG_LOAD_ADDR) 		\
											CFG_YW_ENIGMA2_KERNEL_BASE 	\
											"$filesize"
#define CFG_YW_UPDATE_KERNEL_ENIGMA2	CFG_YW_ERASE_KERNEL_ENIGMA2 ";"	\
											CFG_YW_WRITE_KERNEL_ENIGMA2
#define CFG_YW_UPDATE_KERNEL			CFG_YW_UPDATE_KERNEL_SPARK
#define CFG_YW_ERASE_USERFS_SPARK		CFG_YW_ERASE_CMD " "			\
											CFG_YW_SPARK_USERFS_BASE	\
											CFG_YW_SPARK_USERFS_LEN
#define CFG_YW_WRITE_USERFS_SPARK 		CFG_YW_WRITE_USERFS_SPARK_CMD " "	\
											XSTR(CFG_LOAD_ADDR) 		\
											CFG_YW_SPARK_USERFS_BASE 	\
											"$filesize"
#define CFG_YW_UPDATE_USERFS_SPARK		CFG_YW_ERASE_USERFS_SPARK ";"	\
											CFG_YW_WRITE_USERFS_SPARK
#define CFG_YW_ERASE_USERFS_ENIGMA2 	CFG_YW_ERASE_CMD " "			\
											CFG_YW_ENIGMA2_USERFS_BASE	\
											CFG_YW_ENIGMA2_USERFS_LEN
#define CFG_YW_WRITE_USERFS_ENIGMA2 	CFG_YW_WRITE_USERFS_ENIGMA2_CMD " "	\
											XSTR(CFG_LOAD_ADDR) 		\
											CFG_YW_ENIGMA2_USERFS_BASE 	\
											"$filesize"
#define CFG_YW_UPDATE_USERFS_ENIGMA2	CFG_YW_ERASE_USERFS_ENIGMA2 ";"	\
											CFG_YW_WRITE_USERFS_ENIGMA2
#define CFG_YW_UPDATE_USERFS			CFG_YW_UPDATE_USERFS_SPARK

#define CFG_UBOOT					"u-boot.bin"

#define CFG_SPARK_PATH              "spark"
#define CFG_SPARK_KERNEL_NAME       "mImage"
#define CFG_SPARK_USERFS_NAME       "userfsub.img"

#define CFG_SPARK_KERNEL_FULLNAME   CFG_SPARK_PATH"/"CFG_SPARK_KERNEL_NAME
#define CFG_SPARK_USERFS_FULLNAME   CFG_SPARK_PATH"/"CFG_SPARK_USERFS_NAME

#define CFG_ENIGMA2_PATH            "enigma2"
#define CFG_ENIGMA2_KERNEL_NAME     "uImage"
#define CFG_ENIGMA2_USERFS_NAME     "e2jffs2.img"

#define CFG_ENIGMA2_KERNEL_FULLNAME CFG_ENIGMA2_PATH"/"CFG_ENIGMA2_KERNEL_NAME
#define CFG_ENIGMA2_USERFS_FULLNAME CFG_ENIGMA2_PATH"/"CFG_ENIGMA2_USERFS_NAME
//YWDRIVER_MODI lwj add end
/***** 2011-11-11 D26LF Add:
    Description:增加uboot参数
*/
#define YWCFG_BOOTARGS_SPARK		"console=ttyAS1,115200 "				\
									"rw "									\
									"ramdisk_size=6144 "					\
									"root=/dev/ram0 "						\
									"init=/linuxrc "						\
									"nwhwconf=device:eth0,"					\
											"hwaddr:00:80:E1:12:40:69 "		\
									"ip=192.168.0.69:"						\
											"192.168.3.119:"				\
											"192.168.3.1:"					\
											"255.255.255.0:"				\
											"Spark:"						\
											"eth0:"							\
											"off "							\
									"stmmaceth=msglvl:0,"					\
											"phyaddr:1,"					\
											"watchdog:5000 "				\
									"bigphysarea=7000"

#define YWCFG_BOOTARGS_ENIGMA2		"console=ttyAS1,115200 "				\
									"rw "									\
									"root=/dev/mtdblock6 "					\
									"rootfstype=jffs2 "						\
									"init=/bin/devinit "					\
									"coprocessor_mem=4m@0x40000000,"		\
											"4m@0x40400000 "				\
									"printk=1 "								\
									"nwhwconf=device:eth0,"					\
											"hwaddr:00:80:E1:12:40:61 "		\
									"ip=172.100.100.249:"					\
											"172.100.100.174:"				\
											"172.100.100.174:"				\
											"255.255.255.0:"				\
											"Enigma2:"						\
											"eth0:"							\
											"off "							\
									"stmmaceth=msglvl:0,"					\
											"phyaddr:2,"					\
											"watchdog:5000 "				\
									"bigphysarea=6000"


#define YWCFG_BOOTARGS_NFS			"console=ttyAS0,115200 "				\
									"rw "									\
									"root=/dev/nfs "						\
									"nfsroot=192.168.40.19:/opt/target,"	\
											"nfsvers=2,"					\
											"rsize=4096,"					\
											"wsize=8192,tcp "				\
									"nwhwconf=device:eth0,"					\
											"hwaddr:00:80:E1:12:40:61 "		\
									"ip=192.168.40.61:"						\
											"192.168.40.19:"				\
											"192.168.3.1:"					\
											"255.255.255.0:" 				\
											"LINUX7167:"					\
											"eth0:"							\
											"off "							\
									"stmmaceth=msglvl:0,"					\
											"phyaddr:1,"					\
											"watchdog:5000 "				\
									"bigphysarea=7000"
/***** 2011-11-11 D26LF Add end ****/

#if 0  //YWDRIVER_MODI lwj modify begin
#define CONFIG_EXTRA_ENV_SETTINGS \
		"board=" XSTR(BOARD) "\0" \
		"monitor_base=" XSTR(CFG_MONITOR_BASE) "\0" \
		"monitor_len=" XSTR(CFG_MONITOR_LEN) "\0" \
		"monitor_sec=" MONITOR_SECTORS "\0" \
		"load_addr=" XSTR(CFG_LOAD_ADDR) "\0" \
		"unprot=" \
		  "protect off $monitor_sec\0" \
		"update=" \
		  "erase $monitor_sec;" \
		  "cp.b $load_addr $monitor_base $monitor_len;" \
		  "protect on $monitor_sec\0"
#else
#define CONFIG_EXTRA_ENV_SETTINGS \
		"yw_version=" CONFIG_YW_VERSION_ON_ARG "\0" \
		"board=" XSTR(BOARD) "\0" \
		"monitor_base=0" "\0" \
		"monitor_len=" XSTR(CFG_MONITOR_LEN) "\0" \
		"load_addr=" XSTR(CFG_LOAD_ADDR) "\0" \
        "HOSTNAME=LINUX7167\0" \
		"ethaddr=FF:FF:FF:FF:FF:FF\0" \
		"ipaddr=192.168.40.63\0" \
		"netmask=255.255.255.0\0" \
		"gatewayip=192.168.40.1\0" \
		"serverip=192.168.40.19\0" \
		"bootcmd=" CFG_YW_BOOTCMD_SPARK "\0" \
		"bootcmd_spark=" CFG_YW_BOOTCMD_SPARK "\0" \
		"bootcmd_enigma2=" CFG_YW_BOOTCMD_ENIGMA2 "\0" \
        "kernel_base=" CFG_YW_SPARK_KERNEL_BASE "\0" \
		"kernel_base_spark="CFG_YW_SPARK_KERNEL_BASE"\0" \
		"kernel_base_enigma2="CFG_YW_ENIGMA2_KERNEL_BASE"\0" \
		"kernel_len=" CFG_YW_SPARK_KERNEL_LEN "\0" \
		"kernel_len_spark=" CFG_YW_SPARK_KERNEL_LEN "\0" \
		"kernel_len_enigma2=" CFG_YW_ENIGMA2_KERNEL_LEN "\0" \
		"erase_env=" CFG_YW_ERASE_UBOOT_ENV "\0" \
		"loadu_uboot=" CFG_YW_LOADU_UBOOT "\0" \
		"loadu_kernel=" CFG_YW_LOADU_KERNEL "\0" \
		"loadu_kernel_spark=" CFG_YW_LOADU_KERNEL_SPARK "\0" \
		"loadu_kernel_enigma2=" CFG_YW_LOADU_KERNEL_ENIGMA2 "\0" \
		"loadu_userfs=" CFG_YW_LOADU_USERFS "\0" \
		"loadu_userfs_spark=" CFG_YW_LOADU_USERFS_SPARK "\0" \
		"loadu_userfs_enigma2=" CFG_YW_LOADU_USERFS_ENIGMA2 "\0" \
		"tftp_uboot=" CFG_YW_TFTP_UBOOT "\0" \
		"tftp_kernel=" CFG_YW_TFTP_KERNEL "\0" \
		"tftp_kernel_spark=" CFG_YW_TFTP_KERNEL_SPARK "\0" \
		"tftp_kernel_enigma2=" CFG_YW_TFTP_KERNEL_ENIGMA2 "\0" \
		"tftp_userfs=" CFG_YW_TFTP_USERFS "\0" \
		"tftp_userfs_spark=" CFG_YW_TFTP_USERFS_SPARK "\0" \
		"tftp_userfs_enigma2=" CFG_YW_TFTP_USERFS_ENIGMA2 "\0" \
        "erase_kernel=" CFG_YW_ERASE_KERNEL_SPARK"\0" \
        "erase_userfs=" CFG_YW_ERASE_USERFS_SPARK "\0" \
        "erase_kernel_enigma2=" CFG_YW_ERASE_KERNEL_ENIGMA2"\0" \
        "erase_userfs_enigma2=" CFG_YW_ERASE_USERFS_ENIGMA2 "\0" \
        "write_kernel=" CFG_YW_WRITE_KERNEL_SPARK"\0" \
        "write_userfs=" CFG_YW_WRITE_USERFS_SPARK "\0" \
        "write_kernel_enigma2=" CFG_YW_WRITE_KERNEL_ENIGMA2"\0" \
        "write_userfs_enigma2=" CFG_YW_WRITE_USERFS_ENIGMA2 "\0" \
        "update=" CFG_YW_UPDATE_UBOOT "\0" \
        "update_kernel=" CFG_YW_UPDATE_KERNEL "\0" \
        "update_userfs=" CFG_YW_UPDATE_USERFS "\0" \
        "update_kernel_enigma2=" CFG_YW_UPDATE_KERNEL_ENIGMA2"\0" \
        "update_userfs_enigma2=" CFG_YW_UPDATE_USERFS_ENIGMA2 "\0" \
		"tftp_kernel_name="CFG_SPARK_KERNEL_NAME"\0" \
		"tftp_kernel_name_spark="CFG_SPARK_KERNEL_NAME"\0" \
		"tftp_kernel_name_enigma2="CFG_ENIGMA2_KERNEL_NAME"\0" \
		"tftp_userfs_name="CFG_SPARK_USERFS_NAME"\0" \
		"tftp_userfs_name_spark="CFG_SPARK_USERFS_NAME"\0" \
		"tftp_userfs_name_enigma2="CFG_ENIGMA2_USERFS_NAME"\0" \
		"kernel_name="CFG_SPARK_KERNEL_FULLNAME"\0" \
		"kernel_name_spark="CFG_SPARK_KERNEL_FULLNAME"\0" \
		"kernel_name_enigma2="CFG_ENIGMA2_KERNEL_FULLNAME"\0" \
		"userfs_name="CFG_SPARK_USERFS_FULLNAME"\0" \
		"userfs_name_spark="CFG_SPARK_USERFS_FULLNAME"\0" \
		"userfs_name_enigma2="CFG_ENIGMA2_USERFS_FULLNAME"\0" \
		"userfs_base="CFG_YW_SPARK_USERFS_BASE"\0" \
		"userfs_base_spark="CFG_YW_SPARK_USERFS_BASE"\0" \
		"userfs_base_enigma2="CFG_YW_ENIGMA2_USERFS_BASE"\0" \
		"userfs_len="CFG_YW_SPARK_USERFS_LEN"\0" \
		"userfs_len_spark="CFG_YW_SPARK_USERFS_LEN"\0" \
		"userfs_len_enigma2="CFG_YW_ENIGMA2_USERFS_LEN"\0" \
		"uboot_name=u-boot.bin\0" \
		"ubootnfspath=192.168.40.19:/opt/target\0" \
		"kernelnfspath=192.168.40.19:/opt/target\0" \
		"rootfsnfspath=192.168.40.19:/opt/target\0" \
		"bootfromnfs="YWCFG_BOOTARGS_NFS"\0" \
		"bootargs_flash="YWCFG_BOOTARGS_SPARK"\0" \
		"bootargs="YWCFG_BOOTARGS_SPARK"\0" \
		"bootargs_spark="YWCFG_BOOTARGS_SPARK"\0" \
		"bootargs_enigma2="YWCFG_BOOTARGS_ENIGMA2"\0" \
		"boot_system=spark\0" \
		"ywenv_version=1\0"

#endif
/*--------------------------------------------------------------
 * Command line configuration.
 */

#include <config_cmd_default.h>

#define CONFIG_CMD_ASKENV
#define CONFIG_CMD_NFS
#define CONFIG_CMD_PING
#define CONFIG_CMD_DHCP
#define CONFIG_CMD_MII

/*--------------------------------------------------------------
 * Serial console info
 */

/*
 * We can use one of two methods for the "serial" console.
 * We can either use the (normal hardware) internal ST ASC UART;
 * OR we can use STMicroelectronics' DTF (Data Transfer Format)
 * mechanism over a JTAG link to a remote GDB debugger.
 */
#if 1
#	define CONFIG_STM_ASC_SERIAL	/* use a ST ASC UART */
#else
#	define CONFIG_STM_DTF_SERIAL	/* use DTF over JTAG */
#endif

/* choose which ST ASC UART to use */
#if 1
	/* 9-pin D-type connector on STi7105-SDK-SB daughter board */
#	define CFG_STM_ASC_BASE		ST40_ASC2_REGS_BASE	/* UART #2 */
#else
	/* JN5, 6-way connector - QQQ NOT TESTED */
#	define CFG_STM_ASC_BASE		ST40_ASC3_REGS_BASE	/* UART #3 */
#endif

/*---------------------------------------------------------------
 * Ethernet driver config
 */

/*
 * There are 2 options for ethernet, both use the on-chip ST-GMAC.
 * The choice in PHYs are:
 *    The on-board Micrel KSZ8041FTL
 *    External PHY connected via the MII off-board 15x2 header.
 */

/* are we using the internal ST GMAC device ? */
#define CONFIG_DRIVER_NET_STM_GMAC

/*
 * Select the appropriate base address for the GMAC.
 * Also, choose which PHY to use.
 */
#ifdef CONFIG_DRIVER_NET_STM_GMAC
#	define CFG_STM_STMAC_BASE	0xfd110000ul	/* MAC = STM GMAC0 */
#	define CONFIG_STMAC_KSZ8041			/* PHY = Micrel KSZ8041FTL */
#else
#	undef CONFIG_CMD_NET		/* undefine if no networking at all */
#endif	/* CONFIG_DRIVER_NET_STM_GMAC */

/*  If this board does not have eeprom for ethernet address so allow the user
 *  to set it in the environment
 */
#define CONFIG_ENV_OVERWRITE


/*---------------------------------------------------------------
 * USB driver config
 */

/* Choose if we want USB Mass-Storage Support */
#define CONFIG_SH_STB7100_USB

#ifdef CONFIG_SH_STB7100_USB
#	define CONFIG_CMD_USB
#	define CONFIG_CMD_FAT
#	define CONFIG_USB_OHCI_NEW
#	define CONFIG_USB_STORAGE
#	define CFG_USB_OHCI_CPU_INIT
#	define CFG_USB0_BASE			0xfe100000	/* rear (adjacent to RJ-45) */
#	define CFG_USB1_BASE			0xfea00000	/* front (near corner) */
#	define CFG_USB_BASE			CFG_USB0_BASE
#	define CONFIG_SH_STX_STX7105_USB_PORT0		/* enable Port #0 */
#	define CONFIG_SH_STX_STX7105_USB_OC	1	/* use overcurrent */
#	define CONFIG_SH_STX_STX7105_USB_PW	1	/* use power control */
#	define CFG_USB_OHCI_REGS_BASE		(CFG_USB_BASE+0xffc00)
#	define CFG_USB_OHCI_SLOT_NAME		"ohci"
#	define CFG_USB_OHCI_MAX_ROOT_PORTS	1
#	define LITTLEENDIAN
#endif	/* ifdef CONFIG_SH_STB7100_USB */

/*---------------------------------------------------------------
 * SATA driver config
 */

/* SATA works on cut 3.x of the STx7105 (just one port) */
/* Choose if we want to use a SATA HDD */
//#define CONFIG_SH_STM_SATA

#ifdef CONFIG_SH_STM_SATA
#	define CONFIG_CMD_IDE				/* enable "ide" command set */
#	define CFG_ATA_BASE_ADDR	0xfe209000	/* E-SATA connector */
#	define CFG_ATA_IDE0_OFFSET	0x800		/* Host Controller */
#	define CFG_ATA_REG_OFFSET	0x0
#	define CFG_ATA_DATA_OFFSET	0x0
#	define CFG_ATA_STRIDE		0x4
#	define CFG_IDE_MAXBUS		1
#	define CFG_IDE_MAXDEVICE	1
#endif	/* CONFIG_SH_STM_SATA */

#if defined(CONFIG_SH_STM_SATA) ||	\
    defined(CONFIG_SH_STB7100_USB)
#	define CFG_64BIT_LBA
#	define CONFIG_LBA48
#	define CONFIG_DOS_PARTITION
#	define CONFIG_CMD_EXT2
#endif

/*-----------------------------------------------------------------------
 * Miscellaneous configurable options
 */

#define CFG_HUSH_PARSER		1
#define CONFIG_AUTO_COMPLETE	1
#define CFG_LONGHELP		1		/* undef to save memory		*/
#define CFG_PROMPT		"PDK7105> "	/* Monitor Command Prompt	*/
#define CFG_PROMPT_HUSH_PS2	"> "
#define CFG_CBSIZE		1024
#define CFG_PBSIZE (CFG_CBSIZE+sizeof(CFG_PROMPT)+16) /* Print Buffer Size	*/
#define CFG_MAXARGS		16		/* max number of command args	*/
#define CFG_HZ			1000		/* HZ for timer ticks	*/
#define CFG_LOAD_ADDR		CFG_SDRAM_BASE	/* default load address		*/
#define CFG_BOOTMAPSZ		(32 << 20)	/* initial linux memory size	*/  //YWDRIVER_MODI lwj change from 16 to 20
#define CONFIG_BOOTDELAY	3		/* default delay before executing bootcmd */ //YWDRIVER_MODI lwj change 10 to 3
#define CONFIG_ZERO_BOOTDELAY_CHECK

#define CONFIG_CMDLINE_EDITING

/*-----------------------------------------------------------------------
 * FLASH organization
 */

/* Choose if we want FLASH Support (SPI, NAND &/or NOR devices)
 * With the PDK7105 combination, we may use *both*
 * NOR and NAND flash, at the same time, if we want.
 *
 * Note: by default CONFIG_CMD_FLASH is defined in config_cmd_default.h
 */
#undef CONFIG_CMD_FLASH		/* undefine it, define only if needed */
//#define CONFIG_CMD_FLASH	/* define for NOR flash */
#define CONFIG_CMD_NAND		/* define for NAND flash */
#define CONFIG_SPI_FLASH	/* define for SPI serial flash */

/*-----------------------------------------------------------------------
 * NOR FLASH organization
 */

/* S29GL01GP: 128MiB, 1024 blocks * 128KiB block size */
#ifdef CONFIG_CMD_FLASH				/* NOR flash present ? */
#	define CFG_FLASH_CFI_DRIVER
#	define CFG_FLASH_CFI
#	define CONFIG_FLASH_PROTECT_SINGLE_CELL
#	define CFG_FLASH_PROTECTION	1	/* use hardware flash protection	*/
#	define CFG_MAX_FLASH_BANKS	1	/* max number of memory banks		*/
#	define CFG_MAX_FLASH_SECT	1024	/* max number of sectors on one chip	*/
#	define CFG_FLASH_EMPTY_INFO		/* test if each sector is empty		*/
#	define MTDPARTS_NOR						\
	"physmap-flash:"	/* First NOR flash device */		\
		"256k(U-Boot)"		/* first partition */		\
		",128k(Environment)"					\
		",4M(Kernel)"						\
		",-(RestOfNor0)"	/* last partition */
#	define MTDIDS_NOR						\
	"nor0=physmap-flash"	/* First NOR flash device */
#else
#	undef CONFIG_CMD_IMLS			/* NOR-flash specific */
#	define CFG_NO_FLASH			/* NOR-flash specific */
#endif	/* CONFIG_CMD_FLASH */

/*-----------------------------------------------------------------------
 * NAND FLASH organization
 */

/* HY27UH08AG5B : 2GiB  8-bit, 16384 Blocks (128KiB+4KiB) of 64 Pages (2048+64) */
#ifdef CONFIG_CMD_NAND				/* NAND flash present ? */
#	define CFG_MAX_NAND_DEVICE	1
#	define NAND_MAX_CHIPS		CFG_MAX_NAND_DEVICE
#	define CFG_NAND0_BASE		CFG_EMI_NAND_BASE
#	define CFG_NAND_BASE_LIST	{ CFG_NAND0_BASE }
#	define MTDPARTS_NAND						\
	"gen_nand.1:"		/* First NAND flash device */		\
		"128k(env-nand0)"	/* first partition */		\
		",4M(kernel-nand0)"					\
		",32M(root-nand0)"					\
		",-(RestOfNand0)"	/* last partition */
#	define MTDIDS_NAND						\
	"nand0=gen_nand.1"	/* First NAND flash device */

	/*
	 * Currently, there are 2 main modes to read/write from/to
	 * NAND devices on STM SoCs:
	 *	a) "bit-banging" (can NOT be used in boot-from-NAND)
	 *	b) FLEX-mode (only supported means for boot-from-NAND)
	 * If CFG_NAND_FLEX_MODE is defined, then FLEX-mode will be
	 * used, otherwise, "bit-banging" will be used.
	 */
#	define CFG_NAND_FLEX_MODE	/* define to use NAND FLEX-MODE */

	/*
	 * Do we want to read/write NAND Flash compatible with the ST40's
	 * NAND Controller H/W IP block for "boot-mode"? If we want
	 * to read/write NAND flash that is meant to support booting
	 * from NAND, then we need to use 3 bytes of ECC per 128 byte
	 * record.  If so, then define the "CFG_NAND_ECC_HW3_128" macro.
	 */
#	define CFG_NAND_ECC_HW3_128	/* define for "boot-from-NAND" compatibility */

	/*
	 * If using CFG_NAND_ECC_HW3_128, then we must also define
	 * where the (high watermark) boundary is. That is, the
	 * NAND offset, below which we are in "boot-mode", and
	 * must use 3 bytes of ECC for each 128 byte record.
	 * For this offset (and above) we can use any supported
	 * ECC configuration (e.g 3/256 S/W, or 3/512 H/W).
	 */
#	define CFG_NAND_STM_BOOT_MODE_BOUNDARY (1ul << 20)	/* 1 MiB */

	/*
	 * If we want to store the U-boot environment variables in
	 * the NAND device, then we also need to specify *where* the
	 * environment variables will be stored. Typically this
	 * would be immediately after the U-boot monitor itself.
	 * However, that *may* be a bad block. Define the following
	 * to place the environment in an appropriate good block.
	 */
#	define CFG_NAND_ENV_OFFSET (CFG_MONITOR_LEN + 0x0)	/* immediately after u-boot.bin */
#	define YW_CFG_NAND_ENV_BOUND	(CFG_MONITOR_LEN - 0x60000)	/* After u-boot.bin */ //384k for environment,
#endif
/* CONFIG_CMD_NAND */

/*-----------------------------------------------------------------------
 * SPI SERIAL FLASH organization
 */

/*
 *	Name	Manuf	Device
 *	-----	-----	------
 *	US3	ST	M25P64
 */
#if defined(CONFIG_SPI_FLASH)			/* SPI serial flash present ? */
#	define CONFIG_SPI_FLASH_ST		/* ST M25Pxx (US3) */
#	define CONFIG_SPI			/* enable the SPI driver */
#	define CONFIG_CMD_SPI			/* SPI serial bus command support */
#	define CONFIG_CMD_EEPROM		/* enable the "eeprom" command set */
#	define CFG_EEPROM_WREN		1
#	define CFG_I2C_FRAM			/* to minimize performance degradation */
#	undef  CFG_EEPROM_PAGE_WRITE_DELAY_MS	/* to minimize performance degradation */

	/* choose either the H/W SSC, or S/W "bit-banging" */
#if 1
#	define CONFIG_SOFT_SPI			/* Use S/W "bit-banging" PIO (not the SSC) */
#else
#	define CONFIG_STM_SSC_SPI		/* Use H/W SSC (not S/W "bit-banging" PIO) */
#endif

#if defined(CONFIG_SOFT_SPI)			/* Use "bit-banging" for SPI */
#	define SPI_SCL(val)	do { stx7105_spi_scl((val)); } while (0)
#	define SPI_SDA(val)	do { stx7105_spi_sda((val)); } while (0)
#	define SPI_DELAY	do { udelay(1); } while (0)	/* QQQ: only 500 kHz ??? */
#	define SPI_READ		stx7105_spi_read()
#elif defined(CONFIG_STM_SSC_SPI)		/* Use the H/W SSC for SPI */
#	define CFG_STM_SPI_SSC_BASE	ST40_SSC1_REGS_BASE	/* SSC #1 */
#	define CFG_STM_SPI_FREQUENCY	(5*1000*1000)		/* 5 MHz */
#endif	/* CONFIG_SOFT_SPI */

#endif	/* CONFIG_SPI_FLASH */


/*-----------------------------------------------------------------------
 * Address, size, & location of U-boot's Environment Sector
 */

#define CFG_ENV_SIZE			0x20000	/* 128 KiB of environment data */

#if 1 //YWDRIVER_MODI lwj modify
#if 1 && defined(CONFIG_CMD_FLASH)		/* NOR flash present ? */
#	define CFG_ENV_IS_IN_FLASH		/* environment in NOR flash */
#	define CFG_ENV_OFFSET	CFG_MONITOR_LEN	/* immediately after u-boot.bin */
#	define CFG_ENV_SECT_SIZE	0x20000	/* 128 KiB Sector size */
#elif 1 && defined(CONFIG_CMD_NAND)	&& defined(CFG_BOOT_FROM_NAND)	/* NAND flash present ? */
#	define CFG_ENV_IS_IN_NAND		/* environment in NAND flash */
#	define CFG_ENV_OFFSET	CFG_NAND_ENV_OFFSET
#	if CFG_ENV_SIZE < 0x20000		/* needs to be a multiple of block-size */
#		undef CFG_ENV_SIZE		/* give it just one large-page block */
#		define CFG_ENV_SIZE	0x20000	/* 128 KiB of environment data */
#	endif /* if CFG_ENV_SIZE < 0x20000 */
#elif 1 && defined(CONFIG_SPI_FLASH) && defined(CFG_BOOT_FROM_SPI)		/* SPI serial flash present ? */
#	define CFG_ENV_IS_IN_EEPROM		/* ENV is stored in SPI Serial Flash */
#	define CFG_ENV_OFFSET	(CFG_MONITOR_LEN - 0x60000)	/* immediately after u-boot.bin */
#else
#	define CFG_ENV_IS_NOWHERE		/* ENV is stored in volatile RAM */
#	undef CONFIG_CMD_ENV			/* no need for "saveenv" */
#endif	/* CONFIG_CMD_NAND */
#else
/***** YWDRIVER_MODI 2010-10-11 D26LF Modi:
    Description:防止Uboot使用512k是把环境变量也内置
*/
#if 1
#	define CFG_ENV_OFFSET	(CFG_MONITOR_LEN - 0x60000)	/* After u-boot.bin */ //384k for environment,
#else
#	define CFG_ENV_OFFSET	CFG_MONITOR_LEN /* After u-boot.bin */
#endif
/***** 2010-10-11 D26LF Modi end ****/

#endif
/*----------------------------------------------------------------------
 * JFFS2 + MTD Partition support
 */

#if 1 && (defined(CONFIG_CMD_FLASH) || defined(CONFIG_CMD_NAND))
#	define CONFIG_CMD_JFFS2			/* enable JFFS2 support */
#endif

#if defined(CONFIG_CMD_JFFS2)
#	define CONFIG_JFFS2_CMDLINE		/* mtdparts command line support */
#	define CONFIG_JFFS2_NAND		/* JFFS2 support on NAND Flash */
#	if defined(CONFIG_CMD_FLASH) && defined(CONFIG_CMD_NAND) /* Both NOR + NAND */
#		define MTDPARTS_DEFAULT						\
		"mtdparts="							\
			MTDPARTS_NOR	/* NOR flash devices */			\
			";"		/* delimiter */				\
			MTDPARTS_NAND	/* NAND flash devices */
#		define MTDIDS_DEFAULT						\
			MTDIDS_NOR	/* NOR flash devices */			\
			","		/* delimiter */				\
			MTDIDS_NAND	/* NAND flash devices */
#	elif defined(CONFIG_CMD_FLASH)		/* Only NOR flash devices */
#		define MTDPARTS_DEFAULT	"mtdparts=" MTDPARTS_NOR
#		define MTDIDS_DEFAULT	MTDIDS_NOR
#	elif defined(CONFIG_CMD_NAND)		/* Only NAND flash devices */
#		define MTDPARTS_DEFAULT	"mtdparts=" MTDPARTS_NAND
#		define MTDIDS_DEFAULT	MTDIDS_NAND
#	endif	/* defined(CONFIG_CMD_FLASH) && defined(CONFIG_CMD_NAND) */
#endif	/* CONFIG_CMD_JFFS2 */


/*----------------------------------------------------------------------
 * I2C configuration
 */
#ifndef CONFIG_YW_XPROG
#define YW_CONFIG_VFD  //YWDRIVER_MODI lwj add
#endif

#define CONFIG_CMD_I2C				/* do we want I2C support ? */

#if defined(CONFIG_CMD_I2C)
#include <asm/stx7105reg.h>   //YWDRIVER_MODI lwj add
#if 0 //YWDRIVER_MODI lwj modify
#	define CONFIG_I2C_BUS_C			/* Use I2C Bus "C" */
#else
#define CONFIG_PANEL_SOFT_I2C
#endif

//YWDRIVER_MODI lwj add begin
#define I2C_DA_PORT 2
#define I2C_CL_PORT 2
#define I2C_DA_PIN  1
#define I2C_CL_PIN  0
//YWDRIVER_MODI lwj add end

#	define CONFIG_I2C_CMD_TREE		/* use a "i2c" root command */
#	define CFG_I2C_SLAVE		0x7F	/* I2C slave address - Bogus: master-only in U-Boot */
#	define CONFIG_SOFT_I2C			/* I2C with S/W bit-banging	*/
#	undef  CONFIG_HARD_I2C			/* I2C withOUT hardware support	*/
#	define I2C_ACTIVE		SET_PIO_PIN(PIO_PORT(2), I2C_DA_PIN, STPIO_OUT)
#	define I2C_TRISTATE		SET_PIO_PIN(PIO_PORT(2), I2C_DA_PIN, STPIO_BIDIR)
#	define I2C_SCL(val)		do { stx7105_i2c_scl((val)); } while (0)
#	define I2C_SDA(val)		do { stx7105_i2c_sda((val)); } while (0)
#	define I2C_READ			stx7105_i2c_read()
#	define I2C_INPUT		SET_PIO_PIN(PIO_PORT(2), I2C_DA_PIN, STPIO_IN)
#	define I2C_INIT			{SET_PIO_PIN(PIO_PORT(2), I2C_CL_PIN, STPIO_OUT);\
							SET_PIO_PIN(PIO_PORT(2), I2C_DA_PIN, STPIO_OUT);}



	/*
	 * The "BOGOS" for NDELAY() may be calibrated using the
	 * following code fragment, and measuring (using an oscilloscope)
	 * the frequency of the I2C SCL pin, and adjusting
	 * NDELAY_BOGOS, until the SCL is approximately 100 kHz.
	 * (100kHz has a period of 5us + 5us).
	 *
	 *	printf("just toggling I2C SCL (100kHz frequency) ...\n");
	 *	while (1)
	 *	{
	 *		I2C_SCL(1); NDELAY(5000);
	 *		I2C_SCL(0); NDELAY(5000);
	 *	}
	 */
#	define NDELAY_BOGOS		22	/* Empirical measurement for 1ns */
#	define NDELAY(ns)						\
		do {							\
			const unsigned n_bogo = NDELAY_BOGOS;		\
			const unsigned n_ticks = 			\
				((ns)<n_bogo) ? 1u : (ns)/n_bogo;	\
			volatile unsigned n_count;			\
			for(n_count=0; n_count<n_ticks; n_count++)	\
				;	/* do nothing */		\
		} while(0)

	/*
	 * Note there are 4 * I2C_DELAY per I2C clock cycle
	 * So, 400 kHz requires an I2C delay of 625 ns.
	 * However, this calculation only works if the S/W
	 * overhead in I2C bit-banging is negligible - which it is not!
	 * So, in practice, either I2C_DELAY or CFG_I2C_SPEED will be lower.
	 * The higher the clock frequency, the greater the difference.
	 * Empirical measurement/adjustment is recommended.
	 */
#if 0 //YWDRIVER_MODI lwj modify
#	define CFG_I2C_SPEED	400000				/* I2C speed (Hz) */
#	define I2C_DELAY	do { NDELAY(625); } while (0)	/* 625 ns */
#else
#define CFG_I2C_SPEED		1000000
/*****     2011-12-09     *****/
//YWDRIVER_MODI modify by lf for 加速vfd显示速度 start
#if 1
#define I2C_DELAY		udelay(40)
#else
#define I2C_DELAY		NDELAY(50000)//100kHz frequency
#endif
//YWDRIVER_MODI modify by lf end
#endif
#endif	/* CONFIG_CMD_I2C */


#endif	/* __CONFIG_H */
