#
# (C) Copyright 2007 STMicroelectronics.
# Stuart Menefy <stuart.menefy@st.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y   := init-mb680.o
obj-y   += mb680.o
obj-$(CONFIG_CMD_NAND) += nand.o

