#
# (C) Copyright 2007 STMicroelectronics.
# Stuart Menefy <stuart.menefy@st.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_STM_PDK7105)   := init-pdk7105.o
obj-$(CONFIG_STM_IPIDTV7105)   := init-ipidtv7105.o
obj-y   += pdk7105.o
obj-$(CONFIG_CMD_NAND) += nand.o

