#
# (C) Copyright 2007 STMicroelectronics.
# Stuart Menefy <stuart.menefy@st.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_STM_B2089)   := init-b2089.o
obj-$(CONFIG_STM_B2120)   := init-b2120.o
obj-y   += b2120.o
obj-$(CONFIG_CMD_NAND) += nand.o
