#
# (C) Copyright 2007 STMicroelectronics.
# Stuart Menefy <stuart.menefy@st.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_STM_B2057)   := init-b2057.o
obj-$(CONFIG_STM_B2064)   := init-b2064.o
obj-$(CONFIG_STM_B2067)   := init-b2067.o
obj-$(CONFIG_STM_B2075)   := init-b2075.o
obj-y   += b2057.o
obj-$(CONFIG_CMD_NAND) += nand.o

