/*
 * Copyright (C) STMicroelectronics Ltd. 2002, 2003, 2007-2013
 *
 * andy.sturges@st.com
 * Sean McGoogan <Sean.McGoogan@st.com>
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

/*
 * This is derived from STMicroelectronics gnu toolchain example:
 *   sh-superh-elf/examples/bare/sh4reg/st40reg.h
 */

#ifndef __INCLUDE_STM_STXXXXX_H
#define __INCLUDE_STM_STXXXXX_H

#include <stm/regtype.h>

#if defined(CONFIG_ST40)
#include <asm/sh4reg.h>
#endif /* CONFIG_ST40 */


/*----------------------------------------------------------------------------*/


/*
 * ST40 control registers
 */
#if defined(CONFIG_ST40)

/* Clock Pulse Generator control registers */
#define ST40_CPG_FRQCR			STM_U16_REG(ST40_CPG_REGS_BASE + 0x00)
#define ST40_CPG_STBCR			STM_U8_REG(ST40_CPG_REGS_BASE + 0x04)
#define ST40_CPG_WTCNT			STM_U16_REG(ST40_CPG_REGS_BASE + 0x08)
#define ST40_CPG_WTCNT_R		STM_U8_REG(ST40_CPG_REGS_BASE + 0x08)
#define ST40_CPG_WTCSR			STM_U16_REG(ST40_CPG_REGS_BASE + 0x0c)
#define ST40_CPG_WTCSR_R		STM_U8_REG(ST40_CPG_REGS_BASE + 0x0c)
#define ST40_CPG_STBCR2			STM_U8_REG(ST40_CPG_REGS_BASE + 0x10)
#define ST40_CPG_WTCSR2			STM_U16_REG(ST40_CPG_REGS_BASE + 0x1c)
#define ST40_CPG_WTCSR2_R		STM_U8_REG(ST40_CPG_REGS_BASE + 0x1c)
#define ST40_CPG_FRQCR2			STM_U16_REG(ST40_CPG_REGS_BASE + 0xc0)

#endif /* CONFIG_ST40 */


/*----------------------------------------------------------------------------*/


/*
 * STMicroelectronics control registers
 */

/* Parallel I/O control registers */
#define STM_PIO_POUT(n)		STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x00)
#define STM_PIO_PIN(n)		STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x10)
#define STM_PIO_PC0(n)		STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x20)
#define STM_PIO_PC1(n)		STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x30)
#define STM_PIO_PC2(n)		STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x40)
#define STM_PIO_PCOMP(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x50)
#define STM_PIO_PMASK(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x60)

/* PIO pseudo registers */
#define STM_PIO_SET_POUT(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x04)
#define STM_PIO_CLEAR_POUT(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x08)
#define STM_PIO_SET_PC0(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x24)
#define STM_PIO_CLEAR_PC0(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x28)
#define STM_PIO_SET_PC1(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x34)
#define STM_PIO_CLEAR_PC1(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x38)
#define STM_PIO_SET_PC2(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x44)
#define STM_PIO_CLEAR_PC2(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x48)
#define STM_PIO_SET_PCOMP(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x54)
#define STM_PIO_CLEAR_PCOMP(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x58)
#define STM_PIO_SET_PMASK(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x64)
#define STM_PIO_CLEAR_PMASK(n)	STM_U32_REG(STM_PIO##n##_REGS_BASE + 0x68)

/* Local Memory Interface control registers */
#define STM_LMI_VCR_0(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000000)
#define STM_LMI_VCR_1(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000004)
#define STM_LMI_VCR(n)		STM_U64_REG(STM_LMI##n##_REGS_BASE + 0x000000)
#define STM_LMI_MIM_0(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000008)
#define STM_LMI_MIM_1(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x00000c)
#define STM_LMI_MIM(n)		STM_U64_REG(STM_LMI##n##_REGS_BASE + 0x000008)
#define STM_LMI_SCR_0(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000010)
#define STM_LMI_SCR_1(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000014)
#define STM_LMI_SCR(n)		STM_U64_REG(STM_LMI##n##_REGS_BASE + 0x000010)
#define STM_LMI_STR_0(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000018)
#define STM_LMI_STR_1(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x00001c)
#define STM_LMI_STR(n)		STM_U64_REG(STM_LMI##n##_REGS_BASE + 0x000018)
#define STM_LMI_GCC_0(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000028)
#define STM_LMI_GCC_1(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x00002c)
#define STM_LMI_GCC(n)		STM_U64_REG(STM_LMI##n##_REGS_BASE + 0x000028)
#define STM_LMI_SDRA0_0(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000030)
#define STM_LMI_SDRA0_1(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000034)
#define STM_LMI_SDRA0(n)	STM_U64_REG(STM_LMI##n##_REGS_BASE + 0x000030)
#define STM_LMI_SDRA1_0(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000038)
#define STM_LMI_SDRA1_1(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x00003c)
#define STM_LMI_SDRA1(n)	STM_U64_REG(STM_LMI##n##_REGS_BASE + 0x000038)
#define STM_LMI_CCO_0(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000040)
#define STM_LMI_CCO_1(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000044)
#define STM_LMI_CCO(n)		STM_U64_REG(STM_LMI##n##_REGS_BASE + 0x000040)
#define STM_LMI_SDMR0(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000048)
#define STM_LMI_SDMR1(n)	STM_U32_REG(STM_LMI##n##_REGS_BASE + 0x000050)

/* Enhanced Flash Memory Interface control registers */
#define STM_EMI_VCR_0			STM_U32_REG(STM_EMI_REGS_BASE + 0x0000)
#define STM_EMI_VCR_1			STM_U32_REG(STM_EMI_REGS_BASE + 0x0004)
#define STM_EMI_VCR			STM_U64_REG(STM_EMI_REGS_BASE + 0x0000)
#define STM_EMI_STATUSCFG		STM_U32_REG(STM_EMI_REGS_BASE + 0x0010)
#define STM_EMI_STATUSLOCK		STM_U32_REG(STM_EMI_REGS_BASE + 0x0018)
#define STM_EMI_LOCK			STM_U32_REG(STM_EMI_REGS_BASE + 0x0020)
#define STM_EMI_GENCFG			STM_U32_REG(STM_EMI_REGS_BASE + 0x0028)
#define STM_EMI_SDRAMNOPGEN		STM_U32_REG(STM_EMI_REGS_BASE + 0x0030)
#define STM_EMI_SDRAMMODEREG		STM_U32_REG(STM_EMI_REGS_BASE + 0x0038)
#define STM_EMI_SDRAMINIT		STM_U32_REG(STM_EMI_REGS_BASE + 0x0040)
#define STM_EMI_REFRESHINIT		STM_U32_REG(STM_EMI_REGS_BASE + 0x0048)
#define STM_EMI_FLASHCLKSEL		STM_U32_REG(STM_EMI_REGS_BASE + 0x0050)
#define STM_EMI_SDRAMCLKSEL		STM_U32_REG(STM_EMI_REGS_BASE + 0x0058)
#define STM_EMI_MPXCLKSEL		STM_U32_REG(STM_EMI_REGS_BASE + 0x0060)
#define STM_EMI_CLKENABLE		STM_U32_REG(STM_EMI_REGS_BASE + 0x0068)
#define STM_EMI_BANK0_EMICONFIGDATA0	STM_U32_REG(STM_EMI_REGS_BASE + 0x0100)
#define STM_EMI_BANK0_EMICONFIGDATA1	STM_U32_REG(STM_EMI_REGS_BASE + 0x0108)
#define STM_EMI_BANK0_EMICONFIGDATA2	STM_U32_REG(STM_EMI_REGS_BASE + 0x0110)
#define STM_EMI_BANK0_EMICONFIGDATA3	STM_U32_REG(STM_EMI_REGS_BASE + 0x0118)
#define STM_EMI_BANK1_EMICONFIGDATA0	STM_U32_REG(STM_EMI_REGS_BASE + 0x0140)
#define STM_EMI_BANK1_EMICONFIGDATA1	STM_U32_REG(STM_EMI_REGS_BASE + 0x0148)
#define STM_EMI_BANK1_EMICONFIGDATA2	STM_U32_REG(STM_EMI_REGS_BASE + 0x0150)
#define STM_EMI_BANK1_EMICONFIGDATA3	STM_U32_REG(STM_EMI_REGS_BASE + 0x0158)
#define STM_EMI_BANK2_EMICONFIGDATA0	STM_U32_REG(STM_EMI_REGS_BASE + 0x0180)
#define STM_EMI_BANK2_EMICONFIGDATA1	STM_U32_REG(STM_EMI_REGS_BASE + 0x0188)
#define STM_EMI_BANK2_EMICONFIGDATA2	STM_U32_REG(STM_EMI_REGS_BASE + 0x0190)
#define STM_EMI_BANK2_EMICONFIGDATA3	STM_U32_REG(STM_EMI_REGS_BASE + 0x0198)
#define STM_EMI_BANK3_EMICONFIGDATA0	STM_U32_REG(STM_EMI_REGS_BASE + 0x01c0)
#define STM_EMI_BANK3_EMICONFIGDATA1	STM_U32_REG(STM_EMI_REGS_BASE + 0x01c8)
#define STM_EMI_BANK3_EMICONFIGDATA2	STM_U32_REG(STM_EMI_REGS_BASE + 0x01d0)
#define STM_EMI_BANK3_EMICONFIGDATA3	STM_U32_REG(STM_EMI_REGS_BASE + 0x01d8)
#define STM_EMI_BANK4_EMICONFIGDATA0	STM_U32_REG(STM_EMI_REGS_BASE + 0x0200)
#define STM_EMI_BANK4_EMICONFIGDATA1	STM_U32_REG(STM_EMI_REGS_BASE + 0x0208)
#define STM_EMI_BANK4_EMICONFIGDATA2	STM_U32_REG(STM_EMI_REGS_BASE + 0x0210)
#define STM_EMI_BANK4_EMICONFIGDATA3	STM_U32_REG(STM_EMI_REGS_BASE + 0x0218)
#define STM_EMI_BANK5_EMICONFIGDATA0	STM_U32_REG(STM_EMI_REGS_BASE + 0x0240)
#define STM_EMI_BANK5_EMICONFIGDATA1	STM_U32_REG(STM_EMI_REGS_BASE + 0x0248)
#define STM_EMI_BANK5_EMICONFIGDATA2	STM_U32_REG(STM_EMI_REGS_BASE + 0x0250)
#define STM_EMI_BANK5_EMICONFIGDATA3	STM_U32_REG(STM_EMI_REGS_BASE + 0x0258)

#define STM_EMI_BASEADDRESS(bank)	STM_U32_REG(STM_EMI_REGS_BASE + 0x0800 + (bank)*0x0010)
#define STM_EMI_BANK0_BASEADDRESS	STM_EMI_BASEADDRESS(0)
#define STM_EMI_BANK1_BASEADDRESS	STM_EMI_BASEADDRESS(1)
#define STM_EMI_BANK2_BASEADDRESS	STM_EMI_BASEADDRESS(2)
#define STM_EMI_BANK3_BASEADDRESS	STM_EMI_BASEADDRESS(3)
#define STM_EMI_BANK4_BASEADDRESS	STM_EMI_BASEADDRESS(4)
#define STM_EMI_BANK5_BASEADDRESS	STM_EMI_BASEADDRESS(5)
#define STM_EMI_BANK_ENABLE		STM_U32_REG(STM_EMI_REGS_BASE + 0x0860)

/* EMI NAND (HAMMING) flash registers */
#define STM_EMI_NAND_HAM_REGS_BASE		(STM_EMI_REGS_BASE + 0x1000)
#define STM_EMI_NAND_HAM_BOOTBANK_CFG		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0000)
#define STM_EMI_NAND_HAM_RBN_STA		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0004)
#define STM_EMI_NAND_HAM_INT_EN			STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0010)
#define STM_EMI_NAND_HAM_INT_STA		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0014)
#define STM_EMI_NAND_HAM_INT_CLR		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0018)
#define STM_EMI_NAND_HAM_INT_EDGE_CFG		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x001c)
#define STM_EMI_NAND_HAM_CTL_TIMING		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0040)
#define STM_EMI_NAND_HAM_WEN_TIMING		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0044)
#define STM_EMI_NAND_HAM_REN_TIMING		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0048)
#define STM_EMI_NAND_HAM_BLOCK_ZERO_REMAP_REG	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x004C)
#define STM_EMI_NAND_HAM_FLEXMODE_CFG		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0100)
#define STM_EMI_NAND_HAM_FLEX_MUXCTRL		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0104)
#define STM_EMI_NAND_HAM_FLEX_CS_ALT		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0108)
#define STM_EMI_NAND_HAM_FLEX_DATAWRT_CFG	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x010c)
#define STM_EMI_NAND_HAM_FLEX_DATA_RD_CFG	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0110)
#define STM_EMI_NAND_HAM_FLEX_CMD		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0114)
#define STM_EMI_NAND_HAM_FLEX_ADD_REG		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0118)
#define STM_EMI_NAND_HAM_FLEX_DATA		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0120)
#define STM_EMI_NAND_HAM_VERSION_REG		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0144)
#define STM_EMI_NAND_HAM_ADDRESS_REG_1		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x01E0)
#define STM_EMI_NAND_HAM_ADDRESS_REG_2		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x01E4)
#define STM_EMI_NAND_HAM_ADDRESS_REG_3		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x01E8)
#define STM_EMI_NAND_HAM_MULTI_CS_CONFIG_REG	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x01EC)
#define STM_EMI_NAND_HAM_SEQ_REG1		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0200)
#define STM_EMI_NAND_HAM_SEQ_REG2		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0204)
#define STM_EMI_NAND_HAM_SEQ_REG3		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0208)
#define STM_EMI_NAND_HAM_SEQ_REG4		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x020c)
#define STM_EMI_NAND_HAM_ADD			STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0210)
#define STM_EMI_NAND_HAM_EXTRA_REG		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0214)
#define STM_EMI_NAND_HAM_CMD			STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0218)
#define STM_EMI_NAND_HAM_SEQ_CFG		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x021c)
#define STM_EMI_NAND_HAM_GEN_CFG		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0220)
#define STM_EMI_NAND_HAM_SEQ_STA		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0240)
#define STM_EMI_NAND_HAM_ECC_CHECKCODE_0	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0280)
#define STM_EMI_NAND_HAM_ECC_CHECKCODE_1	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0284)
#define STM_EMI_NAND_HAM_ECC_CHECKCODE_2	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0288)
#define STM_EMI_NAND_HAM_ECC_CHECKCODE_3	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x028c)
#define STM_EMI_NAND_HAM_ECC_CHECKCODE_2X8_0	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0290)
#define STM_EMI_NAND_HAM_ECC_CHECKCODE_2X8_1	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0294)
#define STM_EMI_NAND_HAM_ECC_CHECKCODE_2X8_2	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0298)
#define STM_EMI_NAND_HAM_ECC_CHECKCODE_2X8_3	STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x029C)
#define STM_EMI_NAND_HAM_DATA_FIFO_REG		STM_U32_REG(STM_EMI_NAND_HAM_REGS_BASE + 0x0300)

/* Flex-Mode Data {Read,Write} Config Registers & Flex-Mode {Command,Address} Registers */
#define STM_NAND_FLEX_WAIT_RBn			( 1u << 27 )	/* wait for RBn to be asserted (i.e. ready) */
#define STM_NAND_FLEX_BEAT_COUNT_1		( 1u << 28 )	/* One Beat */
#define STM_NAND_FLEX_BEAT_COUNT_2		( 2u << 28 )	/* Two Beats */
#define STM_NAND_FLEX_BEAT_COUNT_3		( 3u << 28 )	/* Three Beats */
#define STM_NAND_FLEX_BEAT_COUNT_4		( 0u << 28 )	/* Four Beats */
#define STM_NAND_FLEX_ADDR_ADD8_VALID		( 1u << 30 )	/* ADDRESS[8] is valid */
#define STM_NAND_FLEX_CSn_STATUS		( 1u << 31 )	/* Deasserts CSn after current operation completes */

/* Flex-Mode Data-{Read,Write} Config Registers */
#define STM_NAND_FLEX_1_BYTE_PER_BEAT		( 0u << 30 )	/* One Byte per Beat */
#define STM_NAND_FLEX_2_BYTES_PER_BEAT		( 1u << 30 )	/* Two Bytes per Beat */

/* Flex-Mode Configuration Register */
#define STM_NAND_FLEX_CFG_ENABLE_FLEX_MODE	( 1u <<  0 )	/* Enable Flex-Mode operations */
#define STM_NAND_FLEX_CFG_ENABLE_AFM		( 2u <<  0 )	/* Enable Advanced-Flex-Mode operations */
#define STM_NAND_FLEX_CFG_SW_RESET		( 1u <<  3 )	/* Enable Software Reset */
#define STM_NAND_FLEX_CFG_CSn_STATUS		( 1u <<  4 )	/* Deasserts CSn in current Flex bank */


/* EMI NAND (BCH) flash registers */
#define STM_EMI_NAND_BCH_REGS_BASE		(STM_EMI_NAND_HAM_REGS_BASE)
#define STM_EMI_NAND_BCH_BOOTBANK_CFG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x000)
#define STM_EMI_NAND_BCH_RBN_STA		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x004)
#define STM_EMI_NAND_BCH_INT_EN			STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x010)
#define STM_EMI_NAND_BCH_INT_STA		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x014)
#define STM_EMI_NAND_BCH_INT_CLR		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x018)
#define STM_EMI_NAND_BCH_INT_EDGE_CFG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x01C)
#define STM_EMI_NAND_BCH_CTL_TIMING		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x040)
#define STM_EMI_NAND_BCH_WEN_TIMING		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x044)
#define STM_EMI_NAND_BCH_REN_TIMING		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x048)
#define STM_EMI_NAND_BCH_BLOCK_ZERO_REMAP_REG	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x04C)
#define STM_EMI_NAND_BCH_BOOT_STATUS		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x050)
#define STM_EMI_NAND_BCH_FALSE_BOOT_REG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x054)
#define STM_EMI_NAND_BCH_FALSE_BOOT_STATUS	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x058)
#define STM_EMI_NAND_BCH_CONTROLLER_CFG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x100)
#define STM_EMI_NAND_BCH_FLEX_MUXCTRL		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x104)
#define STM_EMI_NAND_BCH_FLEX_DATAWRITE_CONFIG	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x10C)
#define STM_EMI_NAND_BCH_FLEX_DATAREAD_CONFIG	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x110)
#define STM_EMI_NAND_BCH_VERSION_REG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x144)
#define STM_EMI_NAND_BCH_ADDRESS_REG_1		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x1F0)
#define STM_EMI_NAND_BCH_ADDRESS_REG_2		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x1F4)
#define STM_EMI_NAND_BCH_ADDRESS_REG_3		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x1F8)
#define STM_EMI_NAND_BCH_MULTI_CS_CONFIG_REG	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x1FC)
#define STM_EMI_NAND_BCH_SEQ_REG_1		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x200)
#define STM_EMI_NAND_BCH_SEQ_REG_2		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x204)
#define STM_EMI_NAND_BCH_SEQ_REG_3		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x208)
#define STM_EMI_NAND_BCH_SEQ_REG_4		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x20C)
#define STM_EMI_NAND_BCH_ADD			STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x210)
#define STM_EMI_NAND_BCH_EXTRA_REG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x214)
#define STM_EMI_NAND_BCH_CMD			STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x218)
#define STM_EMI_NAND_BCH_GEN_CFG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x220)
#define STM_EMI_NAND_BCH_DELAY_REG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x224)
#define STM_EMI_NAND_BCH_SEQ_CFG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x22C)
#define STM_EMI_NAND_BCH_SEQ_STA		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x270)
#define STM_EMI_NAND_BCH_DATA_BUFFER_ENTRY_0	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x280)
#define STM_EMI_NAND_BCH_DATA_BUFFER_ENTRY_1	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x284)
#define STM_EMI_NAND_BCH_DATA_BUFFER_ENTRY_2	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x288)
#define STM_EMI_NAND_BCH_DATA_BUFFER_ENTRY_3	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x28C)
#define STM_EMI_NAND_BCH_DATA_BUFFER_ENTRY_4	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x290)
#define STM_EMI_NAND_BCH_DATA_BUFFER_ENTRY_5	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x294)
#define STM_EMI_NAND_BCH_DATA_BUFFER_ENTRY_6	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x298)
#define STM_EMI_NAND_BCH_DATA_BUFFER_ENTRY_7	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x29C)
#define STM_EMI_NAND_BCH_ECC_SCORE_REG_A	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x2A0)
#define STM_EMI_NAND_BCH_ECC_SCORE_REG_B	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x2A4)
#define STM_EMI_NAND_BCH_CHECK_STATUS_REG_A	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x2A8)
#define STM_EMI_NAND_BCH_CHECK_STATUS_REG_B	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x2AC)
#define STM_EMI_NAND_BCH_BUFFER_LIST_PTR	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x300)
#define STM_EMI_NAND_BCH_SEQ_PTR_REG		STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x304)
#define STM_EMI_NAND_BCH_ERROR_THRESHOLD_REG	STM_U32_REG(STM_EMI_NAND_BCH_REGS_BASE + 0x308)

/* EMISS NAND BCH STPLUG Registers (Offsets from EMISS_NAND_DMA) */
#define STM_EMISS_NAND_RD_DMA_PAGE_SIZE		STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x000)
#define STM_EMISS_NAND_RD_DMA_MAX_OPCODE_SIZE	STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x004)
#define STM_EMISS_NAND_RD_DMA_MIN_OPCODE_SIZE	STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x008)
#define STM_EMISS_NAND_RD_DMA_MAX_CHUNK_SIZE	STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x00C)
#define STM_EMISS_NAND_RD_DMA_MAX_MESSAGE_SIZE	STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x010)

#define STM_EMISS_NAND_WR_DMA_PAGE_SIZE		STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x100)
#define STM_EMISS_NAND_WR_DMA_MAX_OPCODE_SIZE	STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x104)
#define STM_EMISS_NAND_WR_DMA_MIN_OPCODE_SIZE	STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x108)
#define STM_EMISS_NAND_WR_DMA_MAX_CHUNK_SIZE	STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x10C)
#define STM_EMISS_NAND_WR_DMA_MAX_MESSAGE_SIZE	STM_U32_REG(STM_EMISS_NAND_BCH_DMA_BASE + 0x110)

/* EMI SPI serial flash registers */
#define STM_EMI_SPI_REGS_BASE			(STM_EMI_REGS_BASE + 0x2000)
#define STM_EMI_SPI_CLOCKDIV			STM_U32_REG(STM_EMI_SPI_REGS_BASE + 0x0010)
#define STM_EMI_SPI_MODESELECT			STM_U32_REG(STM_EMI_SPI_REGS_BASE + 0x0018)
#define STM_EMI_SPI_CONFIGDATA			STM_U32_REG(STM_EMI_SPI_REGS_BASE + 0x0020)
#define STM_EMI_SPI_STATUSMODECHANGE		STM_U32_REG(STM_EMI_SPI_REGS_BASE + 0x0028)

/* Synchronous Serial Controller control registers */
#define STM_SSC_BRG(n)			STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0000)
#define STM_SSC_TBUF(n)			STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0004)
#define STM_SSC_RBUF(n)			STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0008)
#define STM_SSC_CTL(n)			STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x000c)
#define STM_SSC_IEN(n)			STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0010)
#define STM_SSC_STA(n)			STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0014)
#define STM_SSC_I2C(n)			STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0018)
#define STM_SSC_SLAD(n)			STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x001c)
#define STM_SSC_REP_START_HOLD(n)	STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0020)
#define STM_SSC_START_HOLD(n)		STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0024)
#define STM_SSC_REP_START_SETUP(n)	STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0028)
#define STM_SSC_DATA_SETUP(n)		STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x002c)
#define STM_SSC_STOP_SETUP(n)		STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0030)
#define STM_SSC_BUS_FREE(n)		STM_U16_REG(STM_SSC##n##_REGS_BASE + 0x0034)
#define STM_SSC_CLR_STA(n)		STM_U32_REG(STM_SSC##n##_REGS_BASE + 0x0080)
#define STM_SSC_AGFR(n)			STM_U32_REG(STM_SSC##n##_REGS_BASE + 0x0100)
#define STM_SSC_PRSC(n)			STM_U32_REG(STM_SSC##n##_REGS_BASE + 0x0104)

/* Asynchronous Serial Controller control registers */
#define STM_ASC_BAUDRATE(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x00)
#define STM_ASC_TXBUFFER(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x04)
#define STM_ASC_RXBUFFER(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x08)
#define STM_ASC_CONTROL(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x0c)
#define STM_ASC_INTENABLE(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x10)
#define STM_ASC_STATUS(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x14)
#define STM_ASC_GUARDTIME(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x18)
#define STM_ASC_TIMEOUT(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x1c)
#define STM_ASC_TXRESET(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x20)
#define STM_ASC_RXRESET(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x24)
#define STM_ASC_RETRIES(n)		STM_U32_REG(STM_ASC##n##_REGS_BASE + 0x28)

/* EMISS/EMIPCISS register space */
#define STM_EMISS_NAND_BCH_DMA_BASE	(STM_EMISS_REGS_BASE + 0x0800)
#define STM_EMISS_CONFIG		STM_U32_REG(STM_EMISS_REGS_BASE + 0x1000)
#define STM_EMISS_NAND_HAMMING_NOT_BCH	(1ul<<6)	/* bit #6 */

#endif /* __INCLUDE_STM_STXXXXX_H */
