/**
*** (c) Copyright Hewlett-Packard Company 1999-2003
***
*** This program is free software; you can redistribute it and/or
*** modify it under the terms of the GNU General Public License
*** as published by the Free Software Foundation; either version
*** 2 of the License, or (at your option) any later version.
***
*** This program is distributed in the hope that it will be useful,
*** but WITHOUT ANY WARRANTY; without even the implied warranty of
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
*** General Public License for more details.
***
*** You should have received a copy of the GNU General Public License
*** along with this program; if not, write to the Free Software
*** Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
***
*** --------------------------------------------------
***                *** DO NOT EDIT ***
***  This file was automatically generated by machgen
*** --------------------------------------------------
**/
/**
*** Runtime architecture definitions (register usage, etc.)
*** Compatibility: LxBE
*** Model: Embedded (non-PIC)
**/

#ifndef __LX_RTA_INCLUDED
#define __LX_RTA_INCLUDED

/* Special registers */
#define STACK_PTR_REG 12
#define STACK_PTR_RG $r0.12
#define LINK_REG 63
#define LINK_RG $r0.63
#define RVP_REG 15
#define RVP_RG $r0.15

/* Branch Registers */
#define BR0_REG 0
#define BR0_RG $b0.0
#define BR1_REG 1
#define BR1_RG $b0.1
#define BR2_REG 2
#define BR2_RG $b0.2
#define BR3_REG 3
#define BR3_RG $b0.3
#define BR4_REG 4
#define BR4_RG $b0.4
#define BR5_REG 5
#define BR5_RG $b0.5
#define BR6_REG 6
#define BR6_RG $b0.6
#define BR7_REG 7
#define BR7_RG $b0.7

/* Argument registers */
#define ARG0_REG 16
#define ARG0_RG $r0.16
#define ARG1_REG 17
#define ARG1_RG $r0.17
#define ARG2_REG 18
#define ARG2_RG $r0.18
#define ARG3_REG 19
#define ARG3_RG $r0.19
#define ARG4_REG 20
#define ARG4_RG $r0.20
#define ARG5_REG 21
#define ARG5_RG $r0.21
#define ARG6_REG 22
#define ARG6_RG $r0.22
#define ARG7_REG 23
#define ARG7_RG $r0.23

/* Other Scratch (Non Argument) Registers */
#define SCR0_REG 8
#define SCR0_RG $r0.8
#define SCR1_REG 9
#define SCR1_RG $r0.9
#define SCR2_REG 10
#define SCR2_RG $r0.10
#define SCR3_REG 11
#define SCR3_RG $r0.11
#define SCR4_REG 24
#define SCR4_RG $r0.24
#define SCR5_REG 25
#define SCR5_RG $r0.25
#define SCR6_REG 26
#define SCR6_RG $r0.26
#define SCR7_REG 27
#define SCR7_RG $r0.27
#define SCR8_REG 28
#define SCR8_RG $r0.28
#define SCR9_REG 29
#define SCR9_RG $r0.29
#define SCR10_REG 30
#define SCR10_RG $r0.30
#define SCR11_REG 31
#define SCR11_RG $r0.31
#define SCR12_REG 32
#define SCR12_RG $r0.32
#define SCR13_REG 33
#define SCR13_RG $r0.33
#define SCR14_REG 34
#define SCR14_RG $r0.34
#define SCR15_REG 35
#define SCR15_RG $r0.35
#define SCR16_REG 36
#define SCR16_RG $r0.36
#define SCR17_REG 37
#define SCR17_RG $r0.37
#define SCR18_REG 38
#define SCR18_RG $r0.38
#define SCR19_REG 39
#define SCR19_RG $r0.39
#define SCR20_REG 40
#define SCR20_RG $r0.40
#define SCR21_REG 41
#define SCR21_RG $r0.41
#define SCR22_REG 42
#define SCR22_RG $r0.42
#define SCR23_REG 43
#define SCR23_RG $r0.43
#define SCR24_REG 44
#define SCR24_RG $r0.44
#define SCR25_REG 45
#define SCR25_RG $r0.45
#define SCR26_REG 46
#define SCR26_RG $r0.46
#define SCR27_REG 47
#define SCR27_RG $r0.47
#define SCR28_REG 48
#define SCR28_RG $r0.48
#define SCR29_REG 49
#define SCR29_RG $r0.49
#define SCR30_REG 50
#define SCR30_RG $r0.50
#define SCR31_REG 51
#define SCR31_RG $r0.51
#define SCR32_REG 52
#define SCR32_RG $r0.52
#define SCR33_REG 53
#define SCR33_RG $r0.53
#define SCR34_REG 54
#define SCR34_RG $r0.54
#define SCR35_REG 55
#define SCR35_RG $r0.55
#define SCR36_REG 56
#define SCR36_RG $r0.56
#define SCR37_REG 57
#define SCR37_RG $r0.57
#define SCR38_REG 58
#define SCR38_RG $r0.58
#define SCR39_REG 59
#define SCR39_RG $r0.59
#define SCR40_REG 60
#define SCR40_RG $r0.60
#define SCR41_REG 61
#define SCR41_RG $r0.61
#define SCR42_REG 62
#define SCR42_RG $r0.62

/* Preserved Registers */
#define PRE0_REG 1
#define PRE0_RG $r0.1
#define PRE1_REG 2
#define PRE1_RG $r0.2
#define PRE2_REG 3
#define PRE2_RG $r0.3
#define PRE3_REG 4
#define PRE3_RG $r0.4
#define PRE4_REG 5
#define PRE4_RG $r0.5
#define PRE5_REG 6
#define PRE5_RG $r0.6
#define PRE6_REG 7
#define PRE6_RG $r0.7
#define PRE7_REG 13
#define PRE7_RG $r0.13
#define PRE8_REG 14
#define PRE8_RG $r0.14
#define PRE_REG_COUNT 9
    /* Preserved: 9 */

/* Kernel/User mode registers */
#define USER0_REG 1
#define USER0_RG $r0.1
#define USER1_REG 2
#define USER1_RG $r0.2
#define USER2_REG 3
#define USER2_RG $r0.3
#define USER3_REG 4
#define USER3_RG $r0.4
#define USER4_REG 5
#define USER4_RG $r0.5
#define USER5_REG 6
#define USER5_RG $r0.6
#define USER6_REG 7
#define USER6_RG $r0.7
#define USER7_REG 8
#define USER7_RG $r0.8
#define USER8_REG 9
#define USER8_RG $r0.9
#define USER9_REG 10
#define USER9_RG $r0.10
#define USER10_REG 11
#define USER10_RG $r0.11
#define USER11_REG 13
#define USER11_RG $r0.13
#define KERN0_REG 14
#define KERN0_RG $r0.14
#define KERN1_REG 15
#define KERN1_RG $r0.15
#define KERN2_REG 16
#define KERN2_RG $r0.16
#define KERN3_REG 17
#define KERN3_RG $r0.17
#define KERN4_REG 18
#define KERN4_RG $r0.18
#define KERN5_REG 19
#define KERN5_RG $r0.19
#define KERN6_REG 20
#define KERN6_RG $r0.20
#define KERN7_REG 21
#define KERN7_RG $r0.21
#define KERN8_REG 22
#define KERN8_RG $r0.22
#define KERN9_REG 23
#define KERN9_RG $r0.23
#define KERN10_REG 24
#define KERN10_RG $r0.24
#define KERN11_REG 25
#define KERN11_RG $r0.25
#define KERN12_REG 26
#define KERN12_RG $r0.26
#define KERN13_REG 27
#define KERN13_RG $r0.27
#define USER12_REG 28
#define USER12_RG $r0.28
#define USER13_REG 29
#define USER13_RG $r0.29
#define USER14_REG 30
#define USER14_RG $r0.30
#define USER15_REG 31
#define USER15_RG $r0.31
#define USER16_REG 32
#define USER16_RG $r0.32
#define USER17_REG 33
#define USER17_RG $r0.33
#define USER18_REG 34
#define USER18_RG $r0.34
#define USER19_REG 35
#define USER19_RG $r0.35
#define USER20_REG 36
#define USER20_RG $r0.36
#define USER21_REG 37
#define USER21_RG $r0.37
#define USER22_REG 38
#define USER22_RG $r0.38
#define USER23_REG 39
#define USER23_RG $r0.39
#define USER24_REG 40
#define USER24_RG $r0.40
#define USER25_REG 41
#define USER25_RG $r0.41
#define USER26_REG 42
#define USER26_RG $r0.42
#define USER27_REG 43
#define USER27_RG $r0.43
#define USER28_REG 44
#define USER28_RG $r0.44
#define USER29_REG 45
#define USER29_RG $r0.45
#define USER30_REG 46
#define USER30_RG $r0.46
#define USER31_REG 47
#define USER31_RG $r0.47
#define USER32_REG 48
#define USER32_RG $r0.48
#define USER33_REG 49
#define USER33_RG $r0.49
#define USER34_REG 50
#define USER34_RG $r0.50
#define USER35_REG 51
#define USER35_RG $r0.51
#define USER36_REG 52
#define USER36_RG $r0.52
#define USER37_REG 53
#define USER37_RG $r0.53
#define USER38_REG 54
#define USER38_RG $r0.54
#define USER39_REG 55
#define USER39_RG $r0.55
#define USER40_REG 56
#define USER40_RG $r0.56
#define USER41_REG 57
#define USER41_RG $r0.57
#define USER42_REG 58
#define USER42_RG $r0.58
#define USER43_REG 59
#define USER43_RG $r0.59
#define USER44_REG 60
#define USER44_RG $r0.60
#define USER45_REG 61
#define USER45_RG $r0.61
#define USER46_REG 62
#define USER46_RG $r0.62
#define KERN_REG_COUNT 14
#define USER_REG_COUNT 47
    /* Kernel: 14, User: 47 */

/* Other Misc stuff */
#define ZERO_REG 0
#define ZERO_RG $r0.0
#define WHICH_SYSCALL_REG 62
#define WHICH_SYSCALL_RG $r0.62
#define SYSCALL_TRAMP_REG 15
#define SYSCALL_TRAMP_RG $r0.15
#define SCRATCHAREASIZE 16

#endif /* __LX_RTA_INCLUDED */
